function [ cifStr ] = cif_str_update( cif_obj, cifStr )
%UNTITLED5 Summary of this function goes here
%   Detailed explanation goes here
[~,end_header]=ismember('_atom_site.pdbx_PDB_model_num ',cifStr);

[~,start_footer]=ismember('# ',cifStr(end_header + 1:end));
atoms=[subsref2(cif_obj,'atom_site.group_PDB'),...
cellstr2(char(subsref2(cif_obj,'atom_site.id'))),...
cellstr2(char(subsref2(cif_obj,'atom_site.type_symbol'))),...
cellstr2(char(subsref2(cif_obj,'atom_site.label_atom_id'))),...
cellstr2(char(subsref2(cif_obj,'atom_site.label_alt_id'))),...
cellstr2(char(subsref2(cif_obj,'atom_site.label_comp_id'))),...
cellstr2(char(subsref2(cif_obj,'atom_site.label_asym_id'))),...
cellstr2(char(subsref2(cif_obj,'atom_site.label_entity_id'))),...
cellstr2(char(subsref2(cif_obj,'atom_site.label_seq_id'))),...
cellstr2(char(subsref2(cif_obj,'atom_site.pdbx_PDB_ins_code'))),...
cellstr2(char(subsref2(cif_obj,'atom_site.Cartn_x'))),...
cellstr2(char(subsref2(cif_obj,'atom_site.Cartn_y'))),...
cellstr2(char(subsref2(cif_obj,'atom_site.Cartn_z'))),...
cellstr2(char(subsref2(cif_obj,'atom_site.occupancy'))),...
cellstr2(char(subsref2(cif_obj,'atom_site.B_iso_or_equiv'))),...
cellstr2(char(subsref2(cif_obj,'atom_site.Cartn_x_esd'))),...
cellstr2(char(subsref2(cif_obj,'atom_site.Cartn_y_esd'))),...
cellstr2(char(subsref2(cif_obj,'atom_site.Cartn_z_esd'))),...
cellstr2(char(subsref2(cif_obj,'atom_site.occupancy_esd'))),...
cellstr2(char(subsref2(cif_obj,'atom_site.B_iso_or_equiv_esd'))),...
cellstr2(char(subsref2(cif_obj,'atom_site.pdbx_formal_charge'))),...
cellstr2(char(subsref2(cif_obj,'atom_site.auth_seq_id'))),...
cellstr2(char(subsref2(cif_obj,'atom_site.auth_comp_id'))),...
cellstr2(char(subsref2(cif_obj,'atom_site.auth_asym_id'))),...
cellstr2(char(subsref2(cif_obj,'atom_site.auth_atom_id'))),...
subsref2(cif_obj,'atom_site.pdbx_PDB_model_num')];

for i = end_header + 1 : start_footer - 1
    cifStr{i} = sprintf(['%s %s %s %s %s %s %s %s %s %s %s %s %s ',...
        '%s %s %s %s %s %s %s %s %s %s %s %s %i' ],...
    atoms{i - end_header,1:25},atoms{i - end_header,26});
    
end

end

function B=subsref2(obj,str)
for ii = 1:numel(obj.cifdat)
    if strcmp(str, obj.cifdat(ii).name)
        B = obj.cifdat(ii).val;
        break;
    end
end
end